SystemOrganization addCategory: #ReactionMapViewer!
SystemOrganization addCategory: 'ReactionMapViewer-GRRMImport'!
SystemOrganization addCategory: 'ReactionMapViewer-Morphs'!
SystemOrganization addCategory: 'ReactionMapViewer-Numerizers'!
SystemOrganization addCategory: 'ReactionMapViewer-Projectors'!
SystemOrganization addCategory: 'ReactionMapViewer-Renderers'!
SystemOrganization addCategory: 'ReactionMapViewer-Support'!
